spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/db_empleados?createDatabaseIfNotExist=true
    url: jdbc:mysql://host.docker.internal:3306/db_empleados?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost
    non-secure-port: 8081
